# Generated by Django 5.0 on 2024-04-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancer_Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_type', models.CharField(max_length=255)),
                ('patient_cohort', models.CharField(max_length=255)),
                ('sample_origin', models.CharField(max_length=255)),
                ('markers_JSON', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('sex', models.BooleanField()),
                ('cancer_samples', models.ManyToManyField(to='api.cancer_sample')),
            ],
        ),
    ]
