# Generated by Django 5.0 on 2024-06-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancersample',
            name='organ_type',
            field=models.CharField(default='pancreas', max_length=255),
        ),
    ]
