# Generated by Django 5.0 on 2024-04-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cancer_sample_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Cancer_Sample',
            new_name='CancerSample',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
