# Generated by Django 5.0 on 2024-05-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cancersample_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancersample',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
