# Generated by Django 5.0 on 2024-04-10 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_doctor_rename_cancer_sample_cancersample_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='cancer_samples',
        ),
        migrations.AddField(
            model_name='cancersample',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancer_samples', to='api.patient'),
        ),
    ]
