# Generated by Django 5.0 on 2024-06-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cancersample_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
