# Generated by Django 5.0 on 2024-04-10 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_patient_cancer_samples_cancersample_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancersample',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
    ]
