# Generated by Django 5.0 on 2024-06-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancersample',
            name='benign_sample_diagnosis',
        ),
    ]
