# Generated by Django 5.0 on 2024-06-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_cancersample_benign_sample_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancersample',
            name='benign_sample_diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
