# Generated by Django 5.0 on 2024-04-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cancersample_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancersample',
            old_name='patient_cohort',
            new_name='benign_sample_diagnosis',
        ),
        migrations.RenameField(
            model_name='cancersample',
            old_name='sample_origin',
            new_name='stage',
        ),
    ]
