# Generated by Django 5.0 on 2024-06-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cancersample_benign_sample_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancersample',
            name='benign_sample_diagnosis',
        ),
    ]
