# Generated by Django 5.0 on 2024-04-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_patient_cohort_cancersample_benign_sample_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancersample',
            name='benign_sample_diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cancersample',
            name='markers_JSON',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cancersample',
            name='stage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
